tecnomarket/app/urls.py
from django.urls import path
from .views import home, galeria, contacto, agregar_producto, listar_productos, \
    modificar_productos, eliminar_productos,registro

urlpatterns = [
    path('', home, name='home'),
    path('galeria/', galeria, name='galeria'),
    path('contacto/', contacto, name='contacto'),
    path('agregar-producto/', agregar_producto, name='agregar_producto'),
    path('listar-productos/', listar_productos, name='listar_productos'),
    path('modificar-productos/<id>/', modificar_productos, name='modificar_productos'),
    path('eliminar-productos/<id>/', eliminar_productos, name='eliminar_productos'),
    path('registro/', registro, name='registro'),
]

tecnomarket/tecnomarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tecnomarket/app/models.py
from django.db import models

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre

opciones_consulta = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"],   
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()
    
    def __str__(self):
        return self.nombre
    

tecnomarket/app/forms.py
from django import forms
from .models import Contacto, Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . validators import MaxSizeFileValidator
from django.forms import ValidationError

class ContactoForm(forms.ModelForm):
    
    class Meta:
        model = Contacto
        #fields = ["nombre", "coreo", "tipo_consulta", "mensaje", "avisos"] #aca se listan 1 x 1 los campos de la clase Contacto
        fields = '__all__' # aca se toma todos los campos de la clase Contacto
        
        
    
class ProductoForm(forms.ModelForm):
    
    nombre = forms.CharField(min_length=3, max_length=50)
    imagen = forms.ImageField(required=False, validators=[MaxSizeFileValidator(max_file_size=2)])
    precio = forms.IntegerField(min_value=1, max_value=1500000)
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        existe = Producto.objects.filter(nombre__iexact=nombre).exists()
        
        if existe:
            raise ValidationError("Este nombre ya existe")
    
    
    class Meta:
        model = Producto
        fields = '__all__'
        
        widgets = {
            "fecha_fabricacion" : forms.SelectDateWidget()
        }
        
class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

tecnomarket/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto
from .forms import ContactoForm, ProductoForm, CustomUserCreationForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required



# Create your views here.
def home(request):
    
    productos = Producto.objects.all()
    data = {
        'productos' : productos
    }
    return render(request, 'app/home.html', data)
#@login_required  restringir si el usuairo no esta registrado y no dejara que entre a la pestaña en este caso a galeria, no lo dejara amenos que tenga un registro
def galeria(request):
    return render(request, 'app/galeria.html')

def contacto(request):
    data = {
        'form' : ContactoForm()
    }
    
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "contacto guardado"
        else:
            data["form"] = formulario
            
    return render(request, 'app/contacto.html',data)

@permission_required('app.add_producto')
def agregar_producto(request):
    
    data = {
        'form' : ProductoForm()
    }
    
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto guardado")
        else:
            data["form"] = formulario
    return render(request, 'app/producto/agregar.html',data)

@permission_required('app.view_producto')
def listar_productos(request):
    
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    
    try:
        paginator = Paginator(productos, 5)
        productos = paginator.page(page)
    except:
        raise Http404("No existe la pagina")
    
    data = {
        'entity' : productos,
        'paginator': paginator
    }
    return render(request, 'app/producto/listar.html',data)

@permission_required('app.change-producto')
def modificar_productos(request, id):
    
    producto = get_object_or_404(Producto, id=id)
    
    data = {
        'form' : ProductoForm(instance=producto)
    }
    
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST,instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto modificado correctamente")
            return redirect(to="listar_productos")
        data["form"] = formulario     
    
    return render(request, 'app/producto/modificar.html',data)

@permission_required('app.delete_producto')
def eliminar_productos(request, id):
    
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    
    messages.success(request, "Producto eliminado correctamente")
    
    return redirect(to="listar_productos")


def registro(request):
    
    data = {
        'form' : CustomUserCreationForm()
    }
    
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"],password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            return redirect(to="home")
        else:
            data["form"] = formulario
            
    return render(request, 'registration/registro.html',data)

tecnomarket/app/templates/app/base.html
<!doctype html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tecnomarket</title>
    {%load static%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


    <link rel="stylesheet" href="{%static 'app/css/estilos.css' %}">
</head>

<body>
    <header id="header">
        <img src="{% static 'app/img/menuiconwhite.png'%}" alt="menu" class="menu" id="menu">
        <div class="contenedor_logo">
            <img src="{% static 'app/img/tecnomarketpngicono.png' %}" alt="logo" class="logo">
        </div>
        <div>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">Contácto</a>
                    </li>
                    <li>
                        <a href="{% url 'galeria' %}">Galería</a>
                    </li>

                    {% if perms.app.add_producto %}
                    <li>
                        <a href="{% url 'agregar_producto'%}">Agregar Producto</a>
                    </li>
                    {% endif %}
                    
                    {% if perms.app.view_producto %}
                    <li>
                        <a href="{% url 'listar_productos'%}">Listado Productos</a>
                    </li>
                    {% endif %}
                   

                    {% if user.is_authenticated %}
                    <li>
                        <form id="form-logout"  action="{% url 'logout' %}" method="POST" style="display: none;"> 
                            {% csrf_token %}
                        </form>
                        <a href="#" onclick="salir()">Cerrar Sesion</a>

                        <script>
                            function salir() {
                                document.getElementById("form-logout").submit();
                            }
                        </script>
                    </li>
                    <li>
                        <a href="#">@{{user.username}}</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">Iniciar Sesion</a>
                    </li>
                    <li>
                        <a href="{% url 'registro' %}">Registrate</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <div id="contenido">




        {% block contenido%}

        {% endblock %}

    </div>
    <footer>
        <footer>
            <div class="marcas">
                <img src="{% static 'app/img/footer/apple.png'%}" alt="apple" style="width: 30px;">
                <img src="{% static 'app/img/footer/lenovo.png'%}" alt="lenovo">
                <img src="{% static 'app/img/footer/microsoft.png'%}" alt="microsoft">
                <img src="{% static 'app/img/footer/samsung.png'%}" alt="samsung">
                <img src="{% static 'app/img/footer/xiaomi.png'%}" alt="xiaomi">
            </div>
            <div class="logo_footer">
                <img src="img/tecnomarketpngicono.png" alt="logo">
            </div>
        </footer>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/menu.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for m in messages %}
    <script>
        Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "success"
        });
    </script>
    {% endfor %}
    {% endif %}

    {% block js %}
    {% endblock %}

</body>

</html>

tecnomarket/app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}

<br>
<br>

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Contactanos!</h2>
                <hr>
                <form action="" class="" method="post">

                    {% csrf_token %}

                    {{ form|crispy }}
                    <hr>
                    <br>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary"></input>
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>

<br>
<br>

{{ mensaje }}


{% endblock %}

tecnomarket/app/templates/app/galeria.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}

<div class="galeria">

    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda1.jpg' %}">
        <img src="{% static 'app/img/tienda/tienda1.jpg' %}">
    </a>

    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda2.jpe' %}g">
        <img src="{% static 'app/img/tienda/tienda2.jpe' %}g">
    </a>

    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda3.jpg' %}">
        <img src="{% static 'app/img/tienda/tienda3.jpg' %}">
    </a>

    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda4.jpg' %}">
        <img src="{% static 'app/img/tienda/tienda4.jpg' %}">
    </a>

    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda5.jpg' %}">
        <img src="{% static 'app/img/tienda/tienda5.jpg' %}">
    </a>


</div>
{% endblock %}

tecnomarket/app/templates/app/home.html
{% extends 'app/base.html'%}

{% load static %}

{% block contenido %}
<div class="productos">
{% load humanize %}
    {% for p in productos %}
    <div class="producto">
        <div class="contenedor">
            {% if  p.imagen%}
            <img src="{{p.imagen.url}}" alt="yoga">
            {% endif %}
        </div>

        <div class="detalles">
            <h5>{{p.marca | capfirst}}</h5>
            <h2>{{p.nombre | title}}</h2>
            <h3>${{p.precio}}</h3>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

tecnomarket/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

tecnomarket/app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Nuevo producto</h2>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                </form>

                {{ mensaje }}
            </div>
        </div>
    </div>
</div>

<br>


{% endblock %}

tecnomarket/app/templates/app/producto/listar.html
{% extends 'app/base.html' %}


{% block js %}
<script>
    function eliminarProducto(id){
        Swal.fire({
            "title": "¿Estás seguro?",
            "text": "No podrás revertir esto!",
            "icon": "question",
            "showCancelButton": true,
            "cancelButtonText": "No, cancelar",
            "confirmButtonText": "Si, eliminar",
            "reverseButtons": true,
            "confirmButtonColor": "#dc3545"
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/eliminar-productos/"+id+"/"
            }
        })
    }
</script>

{% endblock %}
{% block contenido %}

<br>
<div class="card">
    <div class="card-body">

        <h2>Listado de productos</h2>
        <hr>
        <table class=" table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>¿Es Nuevo?</th>
                <th>Opciones</th>
            </tr>

            {% for p in entity %}
            <tr>
                <td>{{p.nombre | title }}</td>
                <td>{{p.precio}}</td>
                <td>{{p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
                </td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_productos' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                    {% endif %}

                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-danger btn-sm">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <hr>
        <div>
            {% include 'app/paginator.html' %}
        </div>
    </div>
</div>
<br>


{% endblock %}

tecnomarket/app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Editar producto</h2>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>
                </form>

                {{ mensaje }}
            </div>
        </div>
    </div>
</div>

<br>


{% endblock %}